/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import FunctionNode_Runtime from "./FunctionNode_Runtime"
import MainPage_Runtime from "./MainPage_Runtime"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=2560;
    static height:number=1920;
    static scaleMode:string="exactfit";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="MainPage.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("FunctionNode_Runtime.ts",FunctionNode_Runtime);
        reg("MainPage_Runtime.ts",MainPage_Runtime);
    }
}
GameConfig.init();